# Generated by Django 2.1.7 on 2019-07-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ml_based_parser', '0002_auto_20190704_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeparse',
            name='time_taken',
        ),
        migrations.RemoveField(
            model_name='resumeparse',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='resumeparse',
            name='is_parse_successful',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resumeparse',
            name='time_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='resumeparse',
            name='time_start',
            field=models.DateTimeField(null=True),
        ),
    ]
